//Definicje telemetrii
#pragma once

//definicje zmiennych telemetrycznych
#define TELEID_AKCEL1X		0
#define TELEID_AKCEL1Y		1
#define TELEID_AKCEL1Z		2
#define TELEID_AKCEL2X		3
#define TELEID_AKCEL2Y		4
#define TELEID_AKCEL2Z		5
#define TELEID_ZYRO1P		6
#define TELEID_ZYRO1Q		7
#define TELEID_ZYRO1R		8
#define TELEID_ZYRO2P		9
#define TELEID_ZYRO2Q		10
#define TELEID_ZYRO2R		11
#define TELEID_MAGNE1X		12
#define TELEID_MAGNE1Y		13
#define TELEID_MAGNE1Z		14
#define TELEID_MAGNE2X		15
#define TELEID_MAGNE2Y		16
#define TELEID_MAGNE2Z		17
#define TELEID_MAGNE3X		18
#define TELEID_MAGNE3Y		19
#define TELEID_MAGNE3Z		20
#define TELEID_KAT_IMU1X	21
#define TELEID_KAT_IMU1Y	22
#define TELEID_KAT_IMU1Z	23
#define TELEID_KAT_IMU2X	24
#define TELEID_KAT_IMU2Y	25
#define TELEID_KAT_IMU2Z	26
#define TELEID_KAT_ZYRO1X	27
#define TELEID_KAT_ZYRO1Y	28
#define TELEID_KAT_ZYRO1Z	29
#define TELEID_CISBEZW1		30
#define TELEID_CISBEZW2		31
#define TELEID_WYSOKOSC1	32
#define TELEID_WYSOKOSC2	33
#define TELEID_CISROZN1		34
#define TELEID_CISROZN2		35
#define TELEID_PREDIAS1		36
#define TELEID_PREDIAS2		37
#define TELEID_TEMPCIS1		38
#define TELEID_TEMPCIS2		39
#define TELEID_TEMPIMU1		40
#define TELEID_TEMPIMU2		41
#define TELEID_TEMPCISR1	42
#define TELEID_TEMPCISR2	43

#define LICZBA_ZMIENNYCH_TELE	44

#define KWANT_CZASU_TELEMETRII	0.01f	//[s]
#define MAX_CZESTOTLIWOSC_TELEMETRII (1 / KWANT_CZASU_TELEMETRII)
#define TEMETETRIA_WYLACZONA	255
