//kody b³êdów
const uint8_t ERR_OK				= 0;	//bez b³êdu
const uint8_t ERR_NOT_CONNECTED		= 1;	//nie po³¹czono z portem szeregowym
const uint8_t ERR_CANT_CONNECT		= 2;	//nie mozna po³¹czyæ z portem 
const uint8_t ERR_INVALID_DATA_SIZE	= 3;	//niew³aœciwy rozmiar danych
const uint8_t ERR_INVALID_COMMAND	= 4;	//niew³asciwe polecenie
const uint8_t ERR_SEND_DATA			= 5;	//b³¹d wysy³ania danych
const uint8_t ERR_RECEIVE_FILE		= 6;	//problem z odbiorem danych
const uint8_t ERR_ZLY_NAGLOWEK		= 7;	//zdekodowano z³y nag³ówek ramki
const uint8_t ERR_ZLY_ADRESAT		= 8;	//ramka jest przeznaczona dla kogoœ innego
const uint8_t ERR_PROCES_TRWA		= 9;
const uint8_t ERR_CRC16				= 10;	//zdekodowano z³¹ sumê kontroln¹
const uint8_t ERR_ZLY_STAN_PROT		= 11;	//wykryto z³y stan protoko³u
const uint8_t ERR_NO_FILE			= 12;	//nie znaleziono takiego pliku
const uint8_t ERR_FILE_READ			= 13;	//problem z odczytem pliku
const uint8_t ERR_SEEK_FILE			= 14;	//problem z ustawieniem pozycji w pliku
const uint8_t ERR_TIMEOUT			= 15;	//timeout oczekiwania na przyjscie danych
const uint8_t ERR_ZLE_DANE			= 16;	//niew³asciwe dane
const uint8_t ERR_NO_DATA_RECEIVED	= 17;	//nie odebrano ¿adnych danych
const uint8_t ERR_OPEN_PORT			= 18;	//nie mozna otworzyæ portu
const uint8_t ERR_CONNECTED			= 19;	//jest ju¿ po³¹czony
const uint8_t ERR_INVALID_ADDRESS	= 20;	//niew³aœciwy adres danych logera
const uint8_t ERR_FILE_FORMAT		= 21;	//niew³aœciwy format pliku
const uint8_t ERR_PLIK_ZA_DLUGI		= 22;	//plik zbyt d³ugi
const uint8_t ERR_NR_ZMIENNEJ_EE	= 23;	//odczytano niew³aœciwy numer zmiennej EEPROM
const uint8_t ERR_WERSJA_CPU		= 24;	//nieprawid³owa wersja CPU
const uint8_t ERR_KASUJ_FLASH_CPU	= 25;	//b³¹d kasowania pamiêci flash kontrolera
const uint8_t ERR_PROGR_FLASH_CPU	= 26;	//b³¹d programowania pamiêci flash kontrolera
const uint8_t ERR_ZLY_TYP_PORTU		= 27;	//niew³aœciwy lub niezdefiniowany typ portu komunikacyjnego
const uint8_t ERR_BLAD_KAMERY		= 28;	//kamera zwróci³a b³¹d
const uint8_t ERR_ZLE_POLECENIE		= 29;	//zdekodowano z³e polecenie
const uint8_t ERR_BRAK_POTWIERDZ	= 30;	//brak potwierdzenia zapisu lub odczytu danych z FRAM