//{{NO_DEPENDENCIES}}
// Plik dołączany wygenerowany przez środowisko Microsoft Visual C++.
// Używany przez: APLSN.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_APLSNTYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_LISTA_ROJU            173
#define IDR_POPUP_WIDOKU                173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_PORT                        310
#define IDD_USTAWIENIA_KAMERY           311
#define IDD_ZAPISZ_FLASH                316
#define IDD_TELEMETRIA                  318
#define IDD_KONFIG_TELEMETRII           318
#define IDD_KONFIG_WYKRESOW             320
#define IDR_MENU1                       322
#define IDR_MENU_WYKRESOW               322
#define IDD_KONFIG_REJESTRATORA         323
#define IDD_KONFIG_PID                  325
#define IDD_DIALOG_DEFINICJE_WRONA      330
#define IDD_MIKSER                      334
#define IDC_COMBO_PORT_COM              1000
#define IDC_COMBO_PREDKOSC              1001
#define IDC_SLIDER_FILTR_D1             1002
#define IDC_SLIDER_FILTR_D2             1003
#define IDC_EDIT_ADRES                  1005
#define IDC_EDIT_PORT_ETH               1006
#define IDC_SLID_SZER_ZDJECIA           1007
#define IDC_SLID_WYS_ZDJECIA            1008
#define IDC_SLID_ZOOM_ZDJECIA2          1009
#define IDC_CHECK_ODWR_PION             1010
#define IDC_CHECK_ODWR_POZ              1011
#define IDC_COMBO_TRYB_DIAGNOSTYCZNY    1012
#define IDC_STATIC_SZEROKOSC            1014
#define IDC_STATIC_WYSOKOSC             1015
#define IDC_RAD_UART                    1016
#define IDC_RAD_ETH                     1017
#define IDC_BUT_CZYTAJ_PLIK             1018
#define IDC_BUT_ZAPISZ_FLASH            1020
#define IDC_BUT_KASUJ_FLASH             1021
#define IDC_LISTA_KOMUNIKATOW           1023
#define IDC_PROGRESS1                   1024
#define IDC_BUT_CZYTAJ_FLASH            1025
#define IDC_BUTTON1                     1026
#define IDC_LIST2                       1031
#define IDC_OKRES_TELEMETRII            1031
#define IDC_LISTA_CZESTOTLIWOSCI        1031
#define IDC_LIST_ZMIENNE_TELE           1041
#define IDC_TREE_WYKRESOW               1043
#define IDC_LISTA_DANYCH                1044
#define IDC_TAB1                        1046
#define IDC_TAB_KANAL_PID               1046
#define IDC_EDIT_KP                     1067
#define IDC_EDIT_KP1                    1067
#define IDC_EDIT_TI                     1068
#define IDC_EDIT_TI1                    1068
#define IDC_EDIT_TD                     1069
#define IDC_EDIT_TD1                    1069
#define IDC_EDIT_LIMIT_CALKI            1070
#define IDC_EDIT_LIMIT_CALKI1           1070
#define IDC_EDIT_FILTRD                 1071
#define IDC_EDIT_FILTRD1                1071
#define IDC_EDIT_MIN_WY1                1072
#define IDC_EDIT_MAX_WY1                1073
#define IDC_EDIT_MIN_WY2                1074
#define IDC_EDIT_MAX_WY2                1075
#define IDC_STATIC_WEJSCIE1             1077
#define IDC_STATIC_WEJSCIE2             1078
#define IDC_STATIC_KP1                  1079
#define IDC_STATIC_KP2                  1080
#define IDC_STATIC_                     1081
#define IDC_EDIT_TI2                    1082
#define IDC_EDIT2                       1083
#define IDC_EDIT_LIMIT_CALKI2           1083
#define IDC_EDIT_NAZWA                  1083
#define IDC_EDIT_KP2                    1084
#define IDC_EDIT_FILTRD2                1085
#define IDC_EDIT_TD2                    1086
#define IDC_RADIO1                      1087
#define IDC_RADIO2                      1088
#define IDC_RADIO3                      1089
#define IDC_RADIO4                      1090
#define IDC_CHECK_KATOWY1               1092
#define IDC_STATIC_FILTR_D1             1093
#define IDC_CHECK_KATOWY2               1094
#define IDC_STATIC_FILTR_D2             1095
#define IDC_CHECK_WYLACZ1               1096
#define IDC_STATIC_ZAJETOSC             1096
#define IDC_CHECK_WYLACZ2               1097
#define IDC_PROGRESS_ZAJETOSC           1097
#define IDC_EDIT_NUMER                  1098
#define IDC_IPADDRESS_DEFINICJE         1099
#define IDC_BUT_KOLOR                   1102
#define IDC_BUTTON2                     1103
#define IDC_MFCCOLOR                    1104
#define IDC_EDIT1                       1105
#define IDC_EDIT3                       1106
#define IDC_EDIT4                       1107
#define IDC_EDIT5                       1108
#define IDC_EDIT6                       1109
#define IDC_EDIT7                       1110
#define IDC_EDIT8                       1111
#define IDC_EDIT9                       1112
#define IDC_EDIT10                      1113
#define IDC_EDIT11                      1114
#define IDC_EDIT12                      1115
#define IDC_EDIT13                      1116
#define IDC_EDIT14                      1117
#define IDC_EDIT15                      1118
#define IDC_EDIT16                      1119
#define ID_POLACZ                       2001
#define ID_WYSLIJ                       2002
#define ID_ZAMKNIJ                      2003
#define ID_POLACZ_COM                   2004
#define ID_ZROB_ZDJECIE                 2005
#define ID_KONFIG_PORT                  2006
#define ID_USTAW_PARKAMERY              2007
#define ID_ZAPISZ_PAMIEC                32790
#define ID_BUT_KONF_TELEMETRII          32792
#define ID_INDICATOR_POLACZ             32793
#define ID_KONFIG_TELEMETRII            32794
#define ID_KONFIG_WYKRES                32795
#define ID_KONFIG_LOGERA                32796
#define ID_KONFIG_REJESTR               32797
#define ID_KONFIG_REJESTRATOR           32798
#define ID_KONFIG_REJESTRATORA          32799
#define ID_KONFIG_WYKRESOW              32800
#define ID_DODAJWYKRESWSP32801          32801
#define ID_DODAJ_WSPOLNY                32802
#define ID_OBS32803                     32803
#define ID_OBS32804                     32804
#define ID_DODAJ_OSOBNY                 32805
#define ID_USUN_WYKRES                  32806
#define ID_USTAWIENIA_USTAWIENIAPID     32807
#define ID_USTAWIENIA_REGULATORY_PID    32808
#define ID_USTAWIENIA_DEFINICJEWRONA    32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
