//{{NO_DEPENDENCIES}}
// Plik dołączany wygenerowany przez środowisko Microsoft Visual C++.
// Używany przez: APLSN.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_APLSNTYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_LISTA_ROJU            173
#define IDR_POPUP_WIDOKU                173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_PORT                        310
#define IDD_USTAWIENIA_KAMERY           311
#define IDT_TIMER_RC                    311
#define IDD_ZAPISZ_FLASH                316
#define IDD_TELEMETRIA                  318
#define IDD_KONFIG_TELEMETRII           318
#define IDD_KONFIG_WYKRESOW             320
#define IDR_MENU1                       322
#define IDR_MENU_WYKRESOW               322
#define IDD_KONFIG_REJESTRATORA         323
#define IDD_KONFIG_PID                  325
#define IDD_DIALOG_DEFINICJE_WRONA      330
#define IDD_MIKSER                      334
#define IDD_ODBIORNIKI_RC               336
#define IDR_ACCELERATOR1                338
#define IDC_COMBO_PORT_COM              1000
#define IDC_COMBO_PREDKOSC              1001
#define IDC_SLIDER_FILTR_D1             1002
#define IDC_SLIDER_FILTR_D2             1003
#define IDC_EDIT_ADRES                  1005
#define IDC_EDIT_PORT_ETH               1006
#define IDC_SLID_SZER_ZDJECIA           1007
#define IDC_SLID_WYS_ZDJECIA            1008
#define IDC_SLID_ZOOM_ZDJECIA           1009
#define IDC_CHECK_ODWR_PION             1010
#define IDC_CHECK_ODWR_POZ              1011
#define IDC_COMBO_TRYB_DIAGNOSTYCZNY    1012
#define IDC_STATIC_SZEROKOSC            1014
#define IDC_STATIC_WYSOKOSC             1015
#define IDC_RAD_UART                    1016
#define IDC_RAD_ETH                     1017
#define IDC_BUT_CZYTAJ_PLIK             1018
#define IDC_BUT_ZAPISZ_FLASH            1020
#define IDC_BUT_KASUJ_FLASH             1021
#define IDC_LISTA_KOMUNIKATOW           1023
#define IDC_PROGRESS1                   1024
#define IDC_BUT_CZYTAJ_FLASH            1025
#define IDC_PROGRESS2                   1025
#define IDC_BUTTON1                     1026
#define IDC_PROGRESS3                   1026
#define IDC_PROGRESS4                   1030
#define IDC_OKRES_TELEMETRII            1031
#define IDC_LISTA_CZESTOTLIWOSCI        1031
#define IDC_PROGRESS5                   1031
#define IDC_PROGRESS6                   1032
#define IDC_PROGRESS7                   1033
#define IDC_PROGRESS8                   1034
#define IDC_PROGRESS9                   1035
#define IDC_PROGRESS10                  1036
#define IDC_PROGRESS11                  1037
#define IDC_PROGRESS12                  1038
#define IDC_PROGRESS13                  1039
#define IDC_PROGRESS14                  1040
#define IDC_LIST_ZMIENNE_TELE           1041
#define IDC_PROGRESS15                  1041
#define IDC_PROGRESS16                  1042
#define IDC_TREE_WYKRESOW               1043
#define IDC_PROGRESS17                  1043
#define IDC_LISTA_DANYCH                1044
#define IDC_PROGRESS18                  1044
#define IDC_PROGRESS19                  1045
#define IDC_TAB_KANAL_PID               1046
#define IDC_PROGRESS20                  1046
#define IDC_PROGRESS21                  1047
#define IDC_PROGRESS22                  1048
#define IDC_EDIT_KP1                    1048
#define IDC_PROGRESS23                  1049
#define IDC_PROGRESS24                  1050
#define IDC_PROGRESS25                  1051
#define IDC_PROGRESS26                  1052
#define IDC_PROGRESS27                  1053
#define IDC_PROGRESS28                  1054
#define IDC_PROGRESS29                  1055
#define IDC_PROGRESS30                  1056
#define IDC_PROGRESS31                  1057
#define IDC_PROGRESS32                  1058
#define IDC_PROGRESS33                  1059
#define IDC_PROGRESS34                  1060
#define IDC_PROGRESS35                  1061
#define IDC_PROGRESS36                  1062
#define IDC_PROGRESS37                  1063
#define IDC_PROGRESS38                  1064
#define IDC_PROGRESS39                  1065
#define IDC_PROGRESS40                  1066
#define IDC_PROGRESS41                  1067
#define IDC_PROGRESS42                  1068
#define IDC_PROGRESS43                  1069
#define IDC_PROGRESS44                  1070
#define IDC_PROGRESS45                  1071
#define IDC_PROGRESS46                  1072
#define IDC_PROGRESS47                  1073
#define IDC_PROGRESS48                  1074
#define IDC_STATIC_WEJSCIE1             1077
#define IDC_STATIC_WEJSCIE2             1078
#define IDC_STATIC_KP1                  1079
#define IDC_STATIC_KP2                  1080
#define IDC_STATIC_                     1081
#define IDC_STATIC_POZIOM_EKSPOZCJI     1081
#define IDC_EDIT_TI2                    1082
#define IDC_EDIT_LIMIT_CALKI2           1083
#define IDC_EDIT_NAZWA                  1083
#define IDC_EDIT_DLUGOSC1               1083
#define IDC_EDIT_KP2                    1084
#define IDC_EDIT_FILTRD2                1085
#define IDC_EDIT_TD2                    1086
#define IDC_RADIO_PPM1                  1087
#define IDC_RADIO_SBUS1                 1088
#define IDC_RADIO_PPM2                  1089
#define IDC_RADIO_SBUS2                 1090
#define IDC_RADIO_SBUS3                 1091
#define IDC_CHECK_KATOWY1               1092
#define IDC_STATIC_FILTR_D1             1093
#define IDC_CHECK_KATOWY2               1094
#define IDC_STATIC_FILTR_D2             1095
#define IDC_CHECK_WYLACZ1               1096
#define IDC_STATIC_ZAJETOSC             1096
#define IDC_CHECK_WYLACZ2               1097
#define IDC_PROGRESS_ZAJETOSC           1097
#define IDC_EDIT_NUMER                  1098
#define IDC_IPADDRESS_DEFINICJE         1099
#define IDC_BUT_KOLOR                   1102
#define IDC_BUTTON2                     1103
#define IDC_MFCCOLOR                    1104
#define IDC_EDIT_KAT1                   1105
#define IDC_EDIT_KAT2                   1106
#define IDC_EDIT_DLUGOSC2               1107
#define IDC_EDIT_KAT3                   1108
#define IDC_EDIT_DLUGOSC3               1109
#define IDC_EDIT_KAT4                   1110
#define IDC_EDIT_DLUGOSC4               1111
#define IDC_EDIT_KAT5                   1112
#define IDC_EDIT_DLUGOSC5               1113
#define IDC_EDIT_KAT6                   1114
#define IDC_EDIT_DLUGOSC6               1115
#define IDC_EDIT_KAT7                   1116
#define IDC_EDIT_DLUGOSC7               1117
#define IDC_EDIT_KAT8                   1118
#define IDC_EDIT_DLUGOSC8               1119
#define IDC_LIST_PREDEFINIOWANE         1120
#define IDC_EDIT_SREDNICA_SMIGLA_MM     1122
#define IDC_EDIT_SREDNICA_SMIGLA_CALE   1123
#define IDC_CHECK_ODSZUMIANIE           1124
#define IDC_SLID_PRZES_POZIOME          1125
#define IDC_SLID_PRZES_PIONOWE          1126
#define IDC_STATIC_ZOOM                 1127
#define IDC_STATIC_PRZES_POZOME         1128
#define IDC_STATIC_PRZES_PIONOWE        1129
#define IDC_SLID_AEC_CZAS               1130
#define IDC_CHECK_EKSPOZYCJA_RECZNA     1131
#define IDC_SLID_AEC_GORNA_GRANICA      1132
#define IDC_SLID_WZMOCNIENIE            1132
#define IDC_COMBO_RC1                   1133
#define IDC_COMBO_RC2                   1134
#define IDC_SLID_AWB_CZERWONY           1135
#define IDC_SLID_AWB_ZIELONY            1136
#define IDC_SLID_AWB_NIEBIESKI          1137
#define IDC_CHECK_BALANS_RECZNY         1138
#define IDC_COMBO_SERWO1                1139
#define IDC_COMBO_SERWO2                1140
#define IDC_COMBO_SERWO3                1141
#define IDC_COMBO_SERWO4                1142
#define IDC_COMBO_SERWO5                1143
#define IDC_COMBO_SERWO6                1144
#define IDC_COMBO_SERWO7                1145
#define IDC_COMBO_SERWO8                1146
#define IDC_COMBO_SERWO9                1147
#define IDC_EDIT_TI1                    1149
#define IDC_EDIT_TD1                    1150
#define IDC_EDIT_LIMIT_CALKI1           1151
#define IDC_EDIT_FILTRD                 1152
#define IDC_EDIT_FILTRD1                1153
#define IDC_EDIT_MIN_WY1                1154
#define IDC_EDIT_MAX_WY1                1155
#define IDC_EDIT_MIN_WY2                1156
#define IDC_EDIT_MAX_WY2                1157
#define IDC_CHECK_ISP1_SKALOWANIE_PIONOWE 1158
#define IDC_CHECK_ISP1_SKALOWANIE_POZIOME 1159
#define IDC_CHECK_ISP1_ROZCIAGANIE_LINI 1160
#define IDC_CHECK_ISP1_USREDNIANIE_CHROMINANCJI 1161
#define IDC_CHECK_ISP1_MACIERZ_KOLOROW  1162
#define IDC_CHECK1_ISP1_AUTO_BALANS_BIELI 1163
#define IDC_CHECK_ISP1_AUTO_BALANS_BIELI 1163
#define IDC_STATIC_AWB_CZERWONA         1164
#define IDC_STATIC_AWB_ZIELONA          1165
#define IDC_STATIC_AWB_NIEBIESKA        1166
#define IDC_SLID_VTS                    1167
#define IDC_CHECK_EKSPOZYCJA_AUTOMATYCZNA 1168
#define IDC_STATIC_CZULOSC              1169
#define IDC_STATIC_BALANS               1170
#define IDC_STATIC_WZMOCNIENIE          1171
#define IDC_STATIC_VTS                  1172
#define IDC_STATIC_CZAS_EKSPOZYCJI      1173
#define IDC_CHECK_KOREKCJA_LENC         1174
#define IDC_CHECK_GAMA_YUV              1175
#define IDC_CHECK_GAMMA_SUROWA          1176
#define IDC_CHECK_ISP0_USUWA_USRED      1177
#define IDC_SLID_PROG_USREDNIANIA_KOLUMN 1178
#define IDC_CHECK_ISP0_ODSZUMIANIE      1179
#define IDC_CHECK_ISP0_USUWANIE_CZARNYCH 1180
#define IDC_CHECK_ISP0_USUWANIE_BIALYCH 1181
#define IDC_CHECK_ISP0_INTERPOLACJA     1182
#define IDC_CHECK_ISP1_CYFROWE_EFEKTY_SPECJALNE 1183
#define IDC_CHECK_ISP1_USTAWIENIE_CHROMINANCJI 1184
#define IDC_BUT_WYSLIJ_DO_KAMERY        1185
#define IDC_SLID_SZEROKOSC_PATRZENIA    1186
#define IDC_SLID_WYSOKOSC_PATRZENIA     1187
#define IDC_STATIC_SZEROKOSC_PATRZENIA  1188
#define IDC_STATIC_WYSOKOSC_PATRZENIA   1189
#define IDC_BUT_WYSLIJ_GRUPOWO          1190
#define IDC_CHECK_RECZNE_WZMOCNIENIE    1191
#define IDC_CHECK_VTS                   1192
#define IDC_SLID_AGC_ADJ                1193
#define IDC_STATIC_AGC_ADJ              1194
#define IDC_COMBO_TYP_OBRAZU            1195
#define IDC_STATIC_KODOWANIE_KOLORU     1197
#define IDC_STATIC_PROG_USUWANIA        1198
#define IDC_SLID_NASYCENIE              1199
#define IDC_STATIC_NASYCENIE            1200
#define IDC_SLID_POZIOM_EXPOZYCJI       1201
#define IDC_BUT_RESET                   1202
#define ID_POLACZ                       2001
#define ID_WYSLIJ                       2002
#define ID_ZAMKNIJ                      2003
#define ID_POLACZ_COM                   2004
#define ID_ZROB_ZDJECIE                 2005
#define ID_KONFIG_PORT                  2006
#define ID_USTAW_PARKAMERY              2007
#define ID_ZAPISZ_PAMIEC                32790
#define ID_BUT_KONF_TELEMETRII          32792
#define ID_INDICATOR_POLACZ             32793
#define ID_KONFIG_TELEMETRII            32794
#define ID_KONFIG_WYKRES                32795
#define ID_KONFIG_LOGERA                32796
#define ID_KONFIG_REJESTR               32797
#define ID_KONFIG_REJESTRATOR           32798
#define ID_KONFIG_REJESTRATORA          32799
#define ID_KONFIG_WYKRESOW              32800
#define ID_DODAJWYKRESWSP32801          32801
#define ID_DODAJ_WSPOLNY                32802
#define ID_OBS32803                     32803
#define ID_OBS32804                     32804
#define ID_DODAJ_OSOBNY                 32805
#define ID_USUN_WYKRES                  32806
#define ID_USTAWIENIA_USTAWIENIAPID     32807
#define ID_USTAWIENIA_REGULATORY_PID    32808
#define ID_USTAWIENIA_DEFINICJEWRONA    32809
#define ID_Menu                         32810
#define ID_USTAWIENIA_MIKSER            32811
#define ID_USTAWIENIA_ODBIORNIKIRC      32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        339
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
